### ISSUE TITLE
Env. variable + issue with filter or gathering devices

### ISSUE THREAD

**Issue by sdargoeuves** [jeremyschulman/ipf-netcfgbu#4]
![image](https://user-images.githubusercontent.com/55829631/132858203-5bdb24ff-f53a-47de-a9da-5e5da358579f.png)
After filling the configuration file, I still had this error:
Error: 'IPF_ADDR'
Not sure if I've missed this in the documentation, so I've added this as an env. variable and could move to the next part.

After that, I get blocked due to the filter, or not be able to find any devices:
![image](https://user-images.githubusercontent.com/55829631/132858809-0288d0ff-de71-4347-a4c1-65ab969db7ec.png)
Is this something you can help with?

**Comment by jeremyschulman** [comment]
Hi @sdargoeuves -
I suspect you might be using the example config file:
https://github.com/jeremyschulman/ipf-netcfgbu/blob/main/ipfnetcfgbu.toml#L18

If that is the case you will need to make changes that are specific to your IP Fabric deployment (such as the server_url) as well as the filter (on line 18).  In the example case, line 18 is excluding any devices in IP Fabric that have a family value of "lap".  So the first thing you should check is what devices are in IP Fabric and tailor your filter to your specific needs.  Alternatively you could remove the filter line out of the config file, and then the tool would attempt to extract the config files for every device you have in inventory.

Hope this helps.

**Comment by sdargoeuves** [comment]
It was my mistake, I didn't configure some variables. After tweaking a few settings I managed to collect the config! I'm closing the issue, it's all good! Thanks for your help!
